config/routes.rb
Shinny::Application.routes.draw do
  root to: "scheduled_activities#index"
  resources :rinks, only: %w( index show )
  resources :scheduled_activities, only: %w( index )
end

app/models/scheduled_activity.rb
class ScheduledActivity < ActiveRecord::Base

  scope :today, -> { where(start_time: Date.today.beginning_of_day..Date.today.end_of_day).order(:start_time) }

  MALE = "M"
  FEMALE = "F"

  belongs_to :activity
  belongs_to :rink

  validates :gender, inclusion: { in: [MALE, FEMALE, nil] }
  validates :activity, :rink, :start_time, :end_time, presence: true
  before_save :denormalize_lat_lon

  geocoded_by :address

  def self.search(opts)
    start_time = opts.start_time || Time.zone.today.beginning_of_day
    end_time = opts.end_time || start_time.end_of_day

    scope = where(end_time: start_time..end_time,
                  activity: opts.activity || Activity.default)
            .limit(opts.limit || 20)
            .near(opts.location, opts.distance || 50, :units => :km)
            .includes(:rink, :activity)
            .order("distance asc, start_time asc")
    scope = scope.where("gender = ? or gender is null", opts.gender) if opts.gender
    if opts.age
      scope = scope.where("start_age is null or start_age <= ?", opts.age)
      scope = scope.where("end_age is null or end_age >= ?", opts.age)
    end
    scope
  end

  def self.conflict_exists?(activity)
    where(rink: activity.rink, start_time: activity.start_time..activity.end_time, original_label: activity.original_label).any?
  end

  def address
    rink.address
  end

  def to_s
    "#{activity.name} @ #{rink.name} : #{start_time} - #{end_time}"
  end

  private

  def denormalize_lat_lon
    if rink
      self.latitude = rink.latitude
      self.longitude = rink.longitude
    end
  end

end

app/controllers/scheduled_activities_controller.rb
class ScheduledActivitiesController < ApplicationController

  after_filter :remember_search_params_for_next_time

  def index
    @activities = Activity.all

    search_params = params[:search] || session[:search] || {}

    @search = Search.new(search_params)

    @scheduled_activities = ScheduledActivity.search(@search)

    respond_to do |format|
      format.html
      format.json { render json: @scheduled_activities.to_json(include: :rink) }
    end
  end

  private

  def remember_search_params_for_next_time
    if @search.remember?
      session[:search] = @search.to_remember
    end
  end
end

app/views/scheduled_activities/index.html.erb
<div class="panel">
  <p>
    <h4 id="search_summary"><%= summarize_search(@search) %></h4>
    <a id="change_search" href="#">[change]</a>
  </p>
  <%= form_for @search, method: :get, url: scheduled_activities_path do |f| %>
    <p>
      <%= f.label :activity_id, "What do you want to do?" %>
      <%= f.select :activity_id do %>
        <%= options_from_collection_for_select(@activities, "id", "name", @search.activity.id) %>
      <% end %>
    </p>
    <p>
      <%= f.label :location, "Where?" %>
      <%= f.text_field :location %>
    </p>
    <p>
      <%= f.label :gender %>
      <%= f.select :gender, [["", nil], ["Male only", ScheduledActivity::MALE], ["Female only", ScheduledActivity::FEMALE]] %>
    </p>
    <p>
      <%= f.label :distance, "Distance (km)" %>
      <%= f.text_field :distance %>
    </p>
    <p>
      <%= f.label :age %>
      <%= f.text_field :age %>
    </p>
    <p>
      <%= f.label :remember, "Remember this for next time" %>
      <%= f.check_box :remember %>
    </p>
    <p>
      <%= f.submit "Update" %>
    </p>
  <% end %>
</div>

<div class="list-group">
  <% @scheduled_activities.each do |activity| %>
    <a class="list-group-item" href="<%= rink_path(activity.rink) %>">
      <h4 class="list-group-item-heading"><%= activity.rink.name %></h4>
      <p class="list-group-item-text">
          <strong><%= format_activity_time(activity.start_time, activity.end_time) %></strong>:
          <%= activity.original_label %>
      </p>
    </a>
  <% end %>
</div>